// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./../src/components/chai/Banner.vue')['default'];
    copy: typeof import('./../src/components/footer/index copy.vue')['default'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
    ElHeader: typeof import('element-plus/es')['ElHeader'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElPopover: typeof import('element-plus/es')['ElPopover'];
    ElTable: typeof import('element-plus/es')['ElTable'];
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
    ElTag: typeof import('element-plus/es')['ElTag'];
    Footer: typeof import('./../src/components/footer/index.vue')['default'];
    'Index copy': typeof import('./../src/components/footer/index copy.vue')['default'];
    Info: typeof import('./../src/components/chai/Info.vue')['default'];
    Product: typeof import('./../src/components/chai/Product.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default'];
    THeader: typeof import('./../src/components/THeader/index.vue')['default'];
  }
}
